### ISSUE TITLE
It doesn't work on the first run

### ISSUE THREAD

**Issue by dgrabla** [JamesPan/hexo-filter-asset-inline#2]
The plugin doesn't work on the first run or right after a `hexo clean`. 

How to reproduce:
1. `hexo clean`
2. `hexo generate` -> In the public folder the HTML is still there with the ?__inline=true
3. `hexo generate` -> Now the <link> tags are replaced by its inlined equivalent

**Comment by jamespan** [comment]
it's by design, first round generate the base result, second round do the inline job

**Comment by madnight** [comment]
I think you should put this into the README.md
